# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWpSEMp01yJ0J4VD98Fwn8nDtXex1mOk
"""

import numpy as np
from numba import cuda
import time

# CUDA kernel
@cuda.jit
def matmul(A, B, C, N):
    row, col = cuda.grid(2)
    if row < N and col < N:
        tmp = 0
        for k in range(N):
            tmp += A[row, k] * B[k, col]
        C[row, col] = tmp


def run_experiment(N, threads_per_block):
    A = np.random.rand(N, N).astype(np.float32)
    B = np.random.rand(N, N).astype(np.float32)
    C = np.zeros((N, N), dtype=np.float32)

    # перенос на GPU
    d_A = cuda.to_device(A)
    d_B = cuda.to_device(B)
    d_C = cuda.to_device(C)

    threads = (threads_per_block, threads_per_block)
    blocks = (N // threads_per_block + 1, N // threads_per_block + 1)

    start = time.time()

    matmul[blocks, threads](d_A, d_B, d_C, N)
    cuda.synchronize()

    end = time.time()

    return end - start

sizes = [200, 400, 800]
configs = [8, 16, 32]

run_experiment(200,8)

for N in sizes:
    print(f"\n======= Matrix size: {N} =======")
    for t in configs:
        ttime = run_experiment(N, t)
        print(f"Threads per block: {t}x{t} |Time: {ttime:.4f} sec")